# Generated by Django 5.0.1 on 2024-01-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_total_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
