# Generated by Django 5.0.1 on 2024-01-30 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_komentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='news.komentar'),
        ),
    ]
