# Generated by Django 5.0.1 on 2024-01-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_article_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
